language: python
python:
- 3.6
- 3.7

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install coverage

script:
  - cd src
  - bash create_aws_environment.sh
  - coverage run -m pytest ../tests/

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - rm coverage.xml
env:
  global:
  - secure: UJ9CLujVrNHgRJJrEMM60RADJC+rikFB2MG4YNUAR0Y836JpxWRFZhmPv7SCmyBR78ZxgqaBBrICqTkQUJDPb4BWGVRjRQRGGesbW7g4MJ3uCfWOEHnapU7+Bgu2quXpkBTC7u5Iv3QKGjmKJlHXbq2bEKgWp6PhzmjNtGGTlgzIDXEiq8FzWbrETkFxLAjNLntV5RJfTQaVQQSOfK7/u1qvfItJYgkM/oZKAivjEqIg3qwEXAjkA03jLko+wKH0XnWTkfyV79s/+YEwRmEl8aXhNwiFy+G22xfbi+9D6UB8oWbQZjir/1F3AH9yb4j0ikvwj+MVt0nt/lsVAbUjKFF5F4flw5OyCAB4hBdMy+84MBv9HQM67hyBWChkd8zzS6IvjNGShLwQfMeFB9PsAS1vE0w79yQ9h2PQZGZoiwiRuH8vnttNFkZLrvaQSOgJboMy7ey4MNq8VxG5mENWicThaq9sryDME9ghIIwyMpcVOwHuAw9pFamyteHp8nXEbBiR7lLxQXQR8s2sx9wEs5hJiyn1A6F4g74IPaezbFZY2LRVQCfUMevygnskcn6pQbF2ALKUka9K50BpLtvhfYoQozU5XgNJAMS7VRmuq511naYz9Pl5CRZUxyrP4MqDlBMQqoDLM0EV7we81/qrEmJIqskfo1J/cIdqWRlkeBc=
  - secure: VjCM2ap/f424AIiarbgST7RBjQySrdEA5Wsb74k0kAyDpIXYtE/5WO6K05pbDt1y1UJBupyvQaQPcxJdBD9/IVBrRx3t1lFTFInMOTb8WpGqLitNoWaitMv6o+RB5+x/8b6oVktZqfmCh+C77/2hX0oJQC7TtLJxSX0D30lcrAlwFXHlxBWxMLy27ylCCx5aQ+vsV2Q/WdYLmQO+OsxDa1ttaChJKBdwIoQ+AabG+85ny+KaiX2BqJ2k2Ec+5ZD0qQOOD61vu4cVd6Ju3Z4qo+GZgTcpudz3p0vqy9UTUAMv8MKKzlzp7PMWB8CDv5GviUZJocyAPEA9+TuF1+J3DgVTMShBqs6QZIrtN5Je5DSjZC56jVBWZcoZ0Uq0YOrsTAzb+p0iy0q7/iMz50RFmMMYm1YeZZ8iNi+z346rY2QSTn5erRWVHQo0SlIfZiX5c6Zm3oVZKGY7zEdyh5ZVRMTpS2F4dQB2YFHb0lbTsQYlk60PtiKkLZxcabosnq9odAQSDFmWg9Gs0kE+7vy0fF9TJ41oV6YM8gdAg95xPaBF7D4nDhNMySqjMLrToSd70i+WhJvEwajcpIS4G3gZ51BL0jE21YGzfCpKzbQPJHPmDO4sucWqULhIMlrbcI8+9JV9bUDy0R9FcRIDjrzLMg6ltMN8iQyCFmKgsa7a8gk=
  - secure: gxUN/DTvGgWJvcc4bDI9I9i3wKPTQN65SFY5ME/fbgIADGCwoXIMeLJdTaGtqCesgLaFhhGUlgcLTWdl4iWRB8Ha/ME6Crc8+J1S/xD2r/H5QZuegpVPIvdch9u1zemt+CM9YI2OpFkwliyDoqawLIrPqVQ8PEsUJZyWw/RdvG532vhkZxqYjJdREJrTsb7BdrcvGm9EkGOlWVyMD0Zf/E2CxxmTDwL97kYiqKdlwwa2MtIgIB6b5imxkcN6No4BVwrsC104Uo/fx47S8F5GD0mowIhb7QKM5nG29AB66Q213c96nP67PmKwEpH9tiQqUeY+b3VZINbU2Z4BgvmIqf4aEi7SLWJlL5hL4a2P5b3iSFMav/PfBzDLbObttUkBX49OzFO066+rTzoBHdv5BTxQPbeHdIck6eJaEno+MQWOzSQM4LY52mQQZndI1vqESqjCsCt9mIFQLcMIlXfqub+vKi7LdHIKtscXcqr43Pap21b9nPTVsAUolt/xH8Ol7w/2R4/Rvl4Y6iOzhsDqTZs2r+/yhDwRNfbtRmNr9N9QxyR6ErWNnlW7pkrevUICCDFBGnDeFaNf3G4cbY5qkVMv5eKp9F8oS9YKF6b6MiQRBRd9QDSYUArcsR/l0LgAyoFYYHpptsWEd1u50BaPAx0AL5/uvTgpjCGqqa4gtHs=
